// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CancelSessionInsights(arg1:string):Promise<void>;

export function CheckForUpdates():Promise<models.UpdateInfo>;

export function ClearCache():Promise<void>;

export function DownloadAndInstallUpdate(arg1:string):Promise<void>;

export function GenerateSessionInsights(arg1:string,arg2:Array<models.ScenarioRecord>,arg3:string,arg4:models.AIOptions):Promise<string>;

export function GetAllBenchmarkProgresses():Promise<Record<number, models.BenchmarkProgress>>;

export function GetBenchmarkProgress(arg1:number):Promise<models.BenchmarkProgress>;

export function GetBenchmarks():Promise<Array<models.Benchmark>>;

export function GetDefaultSettings():Promise<models.Settings>;

export function GetFavoriteBenchmarks():Promise<Array<string>>;

export function GetLastScenarioScores(arg1:string):Promise<Array<models.KovaaksLastScore>>;

export function GetRecentScenarios(arg1:number):Promise<Array<models.ScenarioRecord>>;

export function GetScenarioTrace(arg1:string):Promise<string>;

export function GetSettings():Promise<models.Settings>;

export function GetVersion():Promise<string>;

export function LaunchKovaaksPlaylist(arg1:string):Promise<void>;

export function LaunchKovaaksScenario(arg1:string,arg2:string):Promise<void>;

export function QuitApp():Promise<void>;

export function RefreshAllBenchmarkProgresses():Promise<Record<number, models.BenchmarkProgress>>;

export function ResetSettings(arg1:boolean,arg2:boolean,arg3:boolean,arg4:boolean):Promise<void>;

export function SaveScenarioNote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveSessionNote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetFavoriteBenchmarks(arg1:Array<string>):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartWatcher(arg1:string):Promise<void>;

export function StopWatcher():Promise<void>;

export function UpdateSettings(arg1:models.Settings):Promise<void>;
