// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1);
}

export function GetBenchmarkProgress(arg1) {
  return window['go']['main']['App']['GetBenchmarkProgress'](arg1);
}

export function GetBenchmarks() {
  return window['go']['main']['App']['GetBenchmarks']();
}

export function GetDefaultSettings() {
  return window['go']['main']['App']['GetDefaultSettings']();
}

export function GetFavoriteBenchmarks() {
  return window['go']['main']['App']['GetFavoriteBenchmarks']();
}

export function GetRecentScenarios(arg1) {
  return window['go']['main']['App']['GetRecentScenarios'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LaunchKovaaksPlaylist(arg1) {
  return window['go']['main']['App']['LaunchKovaaksPlaylist'](arg1);
}

export function LaunchKovaaksScenario(arg1, arg2) {
  return window['go']['main']['App']['LaunchKovaaksScenario'](arg1, arg2);
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function SetFavoriteBenchmarks(arg1) {
  return window['go']['main']['App']['SetFavoriteBenchmarks'](arg1);
}

export function StartWatcher(arg1) {
  return window['go']['main']['App']['StartWatcher'](arg1);
}

export function StopWatcher() {
  return window['go']['main']['App']['StopWatcher']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
